#!/usr/bin/env python3
"""
build_industrial_index.py -- regenerates app/src/main/python/industrial_osm_data.py
(ind-v1). NOT part of the app; run on a computer with pyosmium:

    pip install osmium
    curl -L -o iran.osm.pbf https://download.geofabrik.de/asia/iran-latest.osm.pbf
    curl -L -o iran.poly    https://download.geofabrik.de/asia/iran.poly
    python build_industrial_index.py iran.osm.pbf iran.poly <data_date> <file_name>

The tag list below is FROZEN by the cc-v1 plan (2026-10-07). Changing it is
a new method version. Data (c) OpenStreetMap contributors, ODbL 1.0.
"""
import hashlib
import sys

import osmium

KINDS = ["landuse=industrial", "man_made=storage_tank", "man_made=silo",
         "man_made=works", "power=plant"]


def kind_of(tags):
    for i, kv in enumerate(KINDS):
        k, v = kv.split("=")
        if tags.get(k) == v:
            return i
    return None


def main(pbf, poly, data_date, file_name):
    rows = []

    class H(osmium.SimpleHandler):
        def node(self, n):
            k = kind_of(n.tags)
            if k is not None and n.location.valid():
                la, lo = n.location.lat, n.location.lon
                rows.append((k, la, lo, la, lo))

        def area(self, a):
            k = kind_of(a.tags)
            if k is None:
                return
            lats, lons = [], []
            try:
                for ring in a.outer_rings():
                    for nd in ring:
                        lats.append(nd.lat)
                        lons.append(nd.lon)
            except Exception:
                return
            if lats:
                rows.append((k, min(lats), min(lons), max(lats), max(lons)))

    H().apply_file(pbf, locations=True)
    rows = sorted((k, round(a, 6), round(b, 6), round(c, 6), round(d, 6)) for k, a, b, c, d in rows)
    ring = []
    for line in open(poly).read().split("\n")[2:]:
        p = line.split()
        if len(p) == 2:
            ring.append((round(float(p[1]), 6), round(float(p[0]), 6)))
    raw = open(pbf, "rb").read()
    src = {"file": file_name,
           "url": "https://download.geofabrik.de/asia/iran-latest.osm.pbf",
           "data_date": data_date,
           "md5": hashlib.md5(raw).hexdigest(),
           "sha256": hashlib.sha256(raw).hexdigest(),
           "license": "ODbL 1.0, (c) OpenStreetMap contributors",
           "features": len(rows)}
    with open("industrial_osm_data.py", "w") as f:
        f.write('"""GENERATED by build_industrial_index.py -- do not edit by hand.\n\n'
                'Industrial features of Iran from OpenStreetMap (Geofabrik extract\n'
                '%s, data as of %s). Data (c) OpenStreetMap\n'
                'contributors, available under the Open Database License (ODbL 1.0),\n'
                'https://www.openstreetmap.org/copyright.\n\n'
                'Each FEATURES row: (kind index into KINDS, min_lat, min_lon, max_lat,\n'
                'max_lon) -- the bounding box of the mapped outline (a node is a\n'
                'zero-size box). COVERAGE is the Geofabrik iran.poly boundary as\n'
                '(lat, lon) pairs.\n"""\n\n' % (file_name, data_date))
        f.write("SOURCE = %r\n\n" % src)
        f.write("KINDS = %r\n\n" % (KINDS,))
        f.write("COVERAGE = (\n" + "".join("    (%r, %r),\n" % p for p in ring) + ")\n\n")
        f.write("FEATURES = (\n" + "".join("    (%d, %r, %r, %r, %r),\n" % r for r in rows) + ")\n")
    print(len(rows), "features", src["md5"])


if __name__ == "__main__":
    main(*sys.argv[1:5])
