"""
grand_project_db.py

Part of ARIYAN GEO AI's GRAND PROJECT FRAMEWORK (Phase 0 -- persistence
foundation).

PURPOSE: gives ARIYAN a real, persistent, append-only scientific record
that survives across app sessions and across individual investigations --
the schema underlying Grand Project / Hypothesis / Investigation /
Candidate / Evidence Link / Confidence History / Timeline Event /
Calibration Version, per the roadmap agreed 2026-09-13. As of 2026-09-16
(Phase 2.5 Item 3), also underlies Historical Finding / Geographic
Suggestion -- see those tables' own section below for why they are
separate from evidence_link/candidate rather than reusing them.

STORAGE LOCATION -- DELIBERATELY NOT RESOLVED HERE. This module never
decides where its database file lives. It accepts `db_root` as a plain
string parameter to every public function, exactly the same convention
offline_data_manager.py already uses for `offline_data_root`. The actual
value the Kotlin side passes in is `ExternalStorageAccess.offlineDataRoot()
.absolutePath` -- the SAME already-proven-writable directory
MainActivity.kt already uses for offline DEM/NDVI data and for
investigation_status.json (see MainActivity.kt's `offlineDataRoot` lazy
val). This module does not import android/Chaquopy-specific path helpers
and does not guess a second path convention -- it simply opens
"<db_root>/grand_project.db" via plain sqlite3, the same way
offline_data_manager.py writes plain files under its own `offline_data_root`.

DESIGN PRINCIPLES (from the roadmap agreed 2026-09-13):
- Hypothesis objects are EXPLICIT and user-stated per project -- never
  auto-generated by ARIYAN itself (user's own decision).
- Append-only where a table represents scientific history:
  confidence_history and timeline_event rows are NEVER updated or
  deleted after being written -- only ever inserted. This matches the
  Grand Project handoff doc's own rule ("never overwrite historical
  scientific states").
- Rejected/contradicted candidates are NEVER deleted -- only their
  `status` column changes; the row itself persists forever.
- calibration_version exists now but is not populated by anything yet --
  reserved for Phase 5 (self-calibration/learning layer), so Phase 0's
  schema does not need a breaking migration when Phase 5 is built.
- sqlite3 is pure Python stdlib -- confirmed zero new Chaquopy
  dependency risk, unlike the rasterio/GDAL situation this project hit
  and worked around elsewhere (dem_source_mobile.py, ascii_grid.py).

WHAT THIS MODULE DELIBERATELY DOES NOT DO YET:
- No Evidence Graph traversal queries (Phase 2 -- built on top of what
  this module stores, not inside this module).
- No provenance/hash verification (Phase 4 / Steward Stage 2).
- No calibration-suggestion logic (Phase 5) -- `calibration_version`
  is just a table today, nothing writes to it.
- evidence_link.evidence_type remains free-text specifically so a
  future "HISTORICAL_ACCOUNT" value can be added later WITHOUT a
  migration, for the genuinely separate future case of tying an
  already-geocoded historical claim back to an EXISTING DEM candidate's
  lat/lon (post-hoc corroboration). That matching/colocation logic does
  not exist yet and is explicitly NOT what historical_finding/
  geographic_suggestion below are for -- see those tables' own
  docstring note for the distinction.

Every public function here opens its own connection (SQLite handles
this cheaply and this app is single-process); nothing holds a
module-level connection open, so there is no risk of a stale/locked
handle surviving across investigations the way a naive singleton could.
"""

from __future__ import annotations

import json
import os
import sqlite3
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

DB_FILENAME = "grand_project.db"


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _new_id() -> str:
    return uuid.uuid4().hex


def _db_path(db_root: str) -> str:
    return os.path.join(db_root, DB_FILENAME)


def get_connection(db_root: str) -> sqlite3.Connection:
    """Opens (creating if necessary) the Grand Project database under
    `db_root` -- the caller-supplied root, expected to be the SAME
    `offlineDataRoot`/`offline_data_root` value already used elsewhere
    in this project (see module docstring). Ensures the directory
    exists first, exactly like offline_data_manager.py's
    os.makedirs(..., exist_ok=True) calls before writing a manifest.
    Row factory is set to sqlite3.Row so callers get dict-like access
    by column name rather than fragile positional tuples.
    """
    os.makedirs(db_root, exist_ok=True)
    conn = sqlite3.connect(_db_path(db_root))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


_SCHEMA_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS grand_project (
        id                  TEXT PRIMARY KEY,
        name                TEXT NOT NULL,
        scientific_title    TEXT,
        description         TEXT,
        created_at          TEXT NOT NULL,
        last_modified_at    TEXT NOT NULL,
        status              TEXT NOT NULL DEFAULT 'DRAFT',
        current_phase       TEXT,
        research_area_json  TEXT,
        coordinate_ref_sys  TEXT,
        schema_version      INTEGER NOT NULL DEFAULT 1
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS hypothesis (
        id                  TEXT PRIMARY KEY,
        grand_project_id    TEXT NOT NULL,
        statement           TEXT NOT NULL,
        created_at          TEXT NOT NULL,
        current_status      TEXT NOT NULL DEFAULT 'UNKNOWN',
        current_confidence  REAL,
        FOREIGN KEY (grand_project_id) REFERENCES grand_project(id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS investigation (
        id                    TEXT PRIMARY KEY,
        grand_project_id      TEXT NOT NULL,
        objective             TEXT,
        workflow_reference    TEXT,
        parameters_json       TEXT,
        execution_status      TEXT NOT NULL DEFAULT 'PENDING',
        interpretation_summary TEXT,
        created_at            TEXT NOT NULL,
        FOREIGN KEY (grand_project_id) REFERENCES grand_project(id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS candidate (
        id                 TEXT PRIMARY KEY,
        grand_project_id   TEXT NOT NULL,
        investigation_id   TEXT NOT NULL,
        hypothesis_id      TEXT,
        lat                REAL NOT NULL,
        lon                REAL NOT NULL,
        status             TEXT NOT NULL DEFAULT 'GENERATED',
        score              REAL,
        confidence_band    TEXT,
        confidence_numeric REAL,
        created_at         TEXT NOT NULL,
        last_updated_at    TEXT NOT NULL,
        FOREIGN KEY (grand_project_id) REFERENCES grand_project(id),
        FOREIGN KEY (investigation_id) REFERENCES investigation(id),
        FOREIGN KEY (hypothesis_id) REFERENCES hypothesis(id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS evidence_link (
        id              INTEGER PRIMARY KEY AUTOINCREMENT,
        candidate_id    TEXT NOT NULL,
        evidence_type   TEXT NOT NULL,
        relation        TEXT NOT NULL,
        detail_json     TEXT,
        recorded_at     TEXT NOT NULL,
        FOREIGN KEY (candidate_id) REFERENCES candidate(id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS confidence_history (
        id                        INTEGER PRIMARY KEY AUTOINCREMENT,
        candidate_id              TEXT NOT NULL,
        recorded_at               TEXT NOT NULL,
        band                      TEXT,
        numeric_confidence        REAL,
        reasoning_snapshot_json   TEXT,
        triggering_investigation_id TEXT,
        FOREIGN KEY (candidate_id) REFERENCES candidate(id),
        FOREIGN KEY (triggering_investigation_id) REFERENCES investigation(id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS timeline_event (
        id                    INTEGER PRIMARY KEY AUTOINCREMENT,
        grand_project_id      TEXT NOT NULL,
        occurred_at           TEXT NOT NULL,
        event_type            TEXT NOT NULL,
        related_entity_type   TEXT,
        related_entity_id     TEXT,
        description           TEXT,
        FOREIGN KEY (grand_project_id) REFERENCES grand_project(id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS calibration_version (
        id                     INTEGER PRIMARY KEY AUTOINCREMENT,
        created_at             TEXT NOT NULL,
        description            TEXT,
        changed_parameters_json TEXT,
        approved_by_user       INTEGER NOT NULL DEFAULT 0
    )
    """,
    # ==================== ADDED 2026-09-16, Phase 2.5 Item 3 ====================
    # historical_finding / geographic_suggestion are DELIBERATELY separate
    # from evidence_link/candidate, not a reuse of either. evidence_link
    # requires a NOT NULL candidate_id (a candidate requires a completed
    # DEM investigation) -- but historical research (Wikipedia/Wikisource/
    # Internet Archive hits, and the place+radius suggestions extracted
    # from them by historical_claim_extraction_mobile.py) happens BEFORE
    # any DEM candidate exists, often before any investigation has run at
    # all. There is nothing in the pre-2026-09-16 schema this genuinely
    # fits -- forcing it into evidence_link/candidate would misrepresent
    # a pre-investigation research suggestion as if it were post-hoc
    # corroborating evidence for a detection that doesn't yet exist.
    # (The genuinely separate future case -- tying an already-geocoded
    # historical claim back to an EXISTING candidate's lat/lon -- remains
    # unbuilt and would use evidence_link's own reserved
    # evidence_type='HISTORICAL_ACCOUNT' value when it exists; that is
    # NOT what these two tables are for.)
    """
    CREATE TABLE IF NOT EXISTS historical_finding (
        id                TEXT PRIMARY KEY,
        grand_project_id  TEXT NOT NULL,
        hypothesis_id     TEXT,
        source_type       TEXT NOT NULL,
        title             TEXT,
        url               TEXT,
        item_detail_json  TEXT NOT NULL,
        retrieved_at      TEXT NOT NULL,
        created_at        TEXT NOT NULL,
        FOREIGN KEY (grand_project_id) REFERENCES grand_project(id),
        FOREIGN KEY (hypothesis_id) REFERENCES hypothesis(id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS geographic_suggestion (
        id                     TEXT PRIMARY KEY,
        grand_project_id       TEXT NOT NULL,
        hypothesis_id          TEXT,
        historical_finding_id  TEXT,
        kind                   TEXT NOT NULL,
        place_name             TEXT,
        resolved_name          TEXT,
        lat                    REAL,
        lon                    REAL,
        bounding_box_json      TEXT,
        radius_value           REAL,
        radius_unit            TEXT,
        radius_raw_text        TEXT,
        has_proximity_keyword  INTEGER,
        context                TEXT,
        status                 TEXT NOT NULL DEFAULT 'PENDING_REVIEW',
        created_at             TEXT NOT NULL,
        FOREIGN KEY (grand_project_id) REFERENCES grand_project(id),
        FOREIGN KEY (hypothesis_id) REFERENCES hypothesis(id),
        FOREIGN KEY (historical_finding_id) REFERENCES historical_finding(id)
    )
    """,
    # ================== END ADDED 2026-09-16, Phase 2.5 Item 3 ==================
]


def initialize_schema(conn: sqlite3.Connection) -> None:
    """Creates all Grand Project tables if they don't already exist.
    Safe to call on every app start -- CREATE TABLE IF NOT EXISTS is a
    no-op once the schema is already present, matching this project's
    existing "resumable, re-runnable" philosophy used throughout
    offline_data_manager.py."""
    with conn:
        for statement in _SCHEMA_STATEMENTS:
            conn.execute(statement)


# =========================== GRAND PROJECT ===========================

def create_grand_project(
    db_root: str,
    name: str,
    scientific_title: str = "",
    description: str = "",
    research_area: Optional[Dict[str, Any]] = None,
    coordinate_ref_sys: str = "",
    project_id: Optional[str] = None,
) -> str:
    """Creates a new Grand Project row. Returns the new project's id.
    `research_area`, if given, is stored as JSON (e.g. a bbox or polygon
    dict) -- this module does not interpret its shape.

    `project_id`, if given, is used as-is instead of generating a new
    random id -- added so get_or_create_default_grand_project() (see
    grand_project_sync.py) can create a row under a FIXED, known id and
    reliably find that same row again on a later app run, rather than
    every restart creating a fresh random-id project. Existing callers
    (there are none yet in Kotlin, but this keeps the function
    backward-compatible on principle) are entirely unaffected -- the
    default (None) preserves the original random-id behavior exactly."""
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        project_id = project_id or _new_id()
        now = _now_iso()
        with conn:
            conn.execute(
                """
                INSERT INTO grand_project
                    (id, name, scientific_title, description, created_at,
                     last_modified_at, status, current_phase,
                     research_area_json, coordinate_ref_sys, schema_version)
                VALUES (?, ?, ?, ?, ?, ?, 'DRAFT', 'PHASE_0_QUESTION', ?, ?, 1)
                """,
                (
                    project_id, name, scientific_title, description, now, now,
                    json.dumps(research_area) if research_area is not None else None,
                    coordinate_ref_sys,
                ),
            )
        log_timeline_event(
            db_root, project_id, "GRAND_PROJECT_CREATED",
            related_entity_type="grand_project", related_entity_id=project_id,
            description=f"Grand Project '{name}' created.",
        )
        return project_id
    finally:
        conn.close()


def update_grand_project_status(db_root: str, grand_project_id: str, new_status: str) -> None:
    """Updates a Grand Project's lifecycle status. Every transition is
    also logged to timeline_event -- per the handoff doc's rule that a
    project must never silently transition between states."""
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        now = _now_iso()
        with conn:
            conn.execute(
                "UPDATE grand_project SET status = ?, last_modified_at = ? WHERE id = ?",
                (new_status, now, grand_project_id),
            )
        log_timeline_event(
            db_root, grand_project_id, "STATUS_CHANGED",
            related_entity_type="grand_project", related_entity_id=grand_project_id,
            description=f"Status changed to {new_status}.",
        )
    finally:
        conn.close()


# =========================== HYPOTHESIS ===========================

def create_hypothesis(db_root: str, grand_project_id: str, statement: str) -> str:
    """Creates a new, EXPLICIT, user-stated Hypothesis under a Grand
    Project. `statement` must be the user's own words -- ARIYAN never
    auto-generates this text (user's own design decision, 2026-09-13)."""
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        hypothesis_id = _new_id()
        now = _now_iso()
        with conn:
            conn.execute(
                """
                INSERT INTO hypothesis
                    (id, grand_project_id, statement, created_at,
                     current_status, current_confidence)
                VALUES (?, ?, ?, ?, 'UNKNOWN', NULL)
                """,
                (hypothesis_id, grand_project_id, statement, now),
            )
        log_timeline_event(
            db_root, grand_project_id, "HYPOTHESIS_CREATED",
            related_entity_type="hypothesis", related_entity_id=hypothesis_id,
            description=f"Hypothesis stated: {statement}",
        )
        return hypothesis_id
    finally:
        conn.close()


def update_hypothesis_confidence(
    db_root: str, hypothesis_id: str, new_status: str, new_confidence: Optional[float]
) -> None:
    """Updates a Hypothesis's current status/confidence. This is a
    mutable "current state" field by design (mirrors candidate's
    current status/confidence) -- the HISTORY of how it got there lives
    in confidence_history/timeline_event, which are append-only; this
    row is intentionally the one place that's allowed to just reflect
    "right now"."""
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        with conn:
            conn.execute(
                "UPDATE hypothesis SET current_status = ?, current_confidence = ? WHERE id = ?",
                (new_status, new_confidence, hypothesis_id),
            )
    finally:
        conn.close()


# =========================== INVESTIGATION ===========================

def create_investigation(
    db_root: str,
    grand_project_id: str,
    objective: str = "",
    workflow_reference: str = "",
    parameters: Optional[Dict[str, Any]] = None,
) -> str:
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        investigation_id = _new_id()
        now = _now_iso()
        with conn:
            conn.execute(
                """
                INSERT INTO investigation
                    (id, grand_project_id, objective, workflow_reference,
                     parameters_json, execution_status, interpretation_summary,
                     created_at)
                VALUES (?, ?, ?, ?, ?, 'PENDING', NULL, ?)
                """,
                (
                    investigation_id, grand_project_id, objective, workflow_reference,
                    json.dumps(parameters) if parameters is not None else None, now,
                ),
            )
        log_timeline_event(
            db_root, grand_project_id, "INVESTIGATION_STARTED",
            related_entity_type="investigation", related_entity_id=investigation_id,
            description=objective or "Investigation started.",
        )
        return investigation_id
    finally:
        conn.close()


def complete_investigation(
    db_root: str,
    investigation_id: str,
    grand_project_id: str,
    execution_status: str,
    interpretation_summary: str = "",
) -> None:
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        with conn:
            conn.execute(
                "UPDATE investigation SET execution_status = ?, interpretation_summary = ? WHERE id = ?",
                (execution_status, interpretation_summary, investigation_id),
            )
        log_timeline_event(
            db_root, grand_project_id, "INVESTIGATION_COMPLETED",
            related_entity_type="investigation", related_entity_id=investigation_id,
            description=f"Investigation finished with status {execution_status}.",
        )
    finally:
        conn.close()


# =========================== CANDIDATE ===========================

def create_candidate(
    db_root: str,
    grand_project_id: str,
    investigation_id: str,
    lat: float,
    lon: float,
    score: Optional[float] = None,
    hypothesis_id: Optional[str] = None,
) -> str:
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        candidate_id = _new_id()
        now = _now_iso()
        with conn:
            conn.execute(
                """
                INSERT INTO candidate
                    (id, grand_project_id, investigation_id, hypothesis_id,
                     lat, lon, status, score, confidence_band,
                     confidence_numeric, created_at, last_updated_at)
                VALUES (?, ?, ?, ?, ?, ?, 'GENERATED', ?, NULL, NULL, ?, ?)
                """,
                (
                    candidate_id, grand_project_id, investigation_id, hypothesis_id,
                    lat, lon, score, now, now,
                ),
            )
        log_timeline_event(
            db_root, grand_project_id, "CANDIDATE_GENERATED",
            related_entity_type="candidate", related_entity_id=candidate_id,
            description=f"Candidate generated at ({lat:.6f}, {lon:.6f}).",
        )
        return candidate_id
    finally:
        conn.close()


def update_candidate_status(
    db_root: str, grand_project_id: str, candidate_id: str, new_status: str
) -> None:
    """Changes ONLY the status column -- the row itself is never
    deleted, including for CONTRADICTED/REJECTED candidates. Per the
    handoff doc (section 10) and the user's own treasure-hunt framing:
    a dead end is retained evidence, not discarded data."""
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        now = _now_iso()
        with conn:
            conn.execute(
                "UPDATE candidate SET status = ?, last_updated_at = ? WHERE id = ?",
                (new_status, now, candidate_id),
            )
        log_timeline_event(
            db_root, grand_project_id, "CANDIDATE_STATUS_CHANGED",
            related_entity_type="candidate", related_entity_id=candidate_id,
            description=f"Candidate status changed to {new_status}.",
        )
    finally:
        conn.close()


def update_candidate_confidence(
    db_root: str,
    candidate_id: str,
    band: Optional[str],
    numeric_confidence: Optional[float],
) -> None:
    """Updates the candidate row's OWN "current confidence" columns
    (confidence_band/confidence_numeric) -- ADDED for Phase 1 wiring.
    This is deliberately a plain UPDATE, not append-only: the candidate
    row is meant to reflect "what do we currently think," while the
    FULL history of how that number changed over time lives in
    confidence_history (append-only, see record_confidence_history()
    above). Callers doing a real Steward re-evaluation should call
    BOTH functions together -- record_confidence_history() to preserve
    the trail, and this function to keep the candidate's own row
    current -- exactly the same two-tier pattern the Grand Project
    handoff doc itself describes (section 15: "factual memory" vs.
    "current scientific interpretation")."""
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        now = _now_iso()
        with conn:
            conn.execute(
                "UPDATE candidate SET confidence_band = ?, confidence_numeric = ?, last_updated_at = ? WHERE id = ?",
                (band, numeric_confidence, now, candidate_id),
            )
    finally:
        conn.close()


def link_candidate_to_hypothesis(db_root: str, candidate_id: str, hypothesis_id: str) -> None:
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        now = _now_iso()
        with conn:
            conn.execute(
                "UPDATE candidate SET hypothesis_id = ?, last_updated_at = ? WHERE id = ?",
                (hypothesis_id, now, candidate_id),
            )
    finally:
        conn.close()


# =========================== EVIDENCE LINK ===========================

def add_evidence_link(
    db_root: str,
    candidate_id: str,
    evidence_type: str,
    relation: str,
    detail: Optional[Dict[str, Any]] = None,
) -> int:
    """`evidence_type` is deliberately free-text (not an enum/CHECK
    constraint) -- so a future Phase 2.5 value like
    'HISTORICAL_ACCOUNT' can be inserted without a schema migration.
    `relation` is expected to be one of 'supports' / 'contradicts' /
    'neutral', matching the handoff doc's own vocabulary, but is not
    constrained here either, for the same forward-compatibility reason.
    `detail` is stored as-is as JSON -- intended to be the SAME
    `*_evidence_detail` dict this project's existing evidence sources
    (DEM/NDVI/Thermal/Optical/SAR/GPR/ERT/Stability/Temporal Persistence/
    DEM Cross-Check) already produce, reused rather than reshaped."""
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        now = _now_iso()
        with conn:
            cursor = conn.execute(
                """
                INSERT INTO evidence_link
                    (candidate_id, evidence_type, relation, detail_json, recorded_at)
                VALUES (?, ?, ?, ?, ?)
                """,
                (candidate_id, evidence_type, relation,
                 json.dumps(detail) if detail is not None else None, now),
            )
            return cursor.lastrowid
    finally:
        conn.close()


# =========================== CONFIDENCE HISTORY ===========================

def record_confidence_history(
    db_root: str,
    candidate_id: str,
    band: Optional[str],
    numeric_confidence: Optional[float],
    reasoning_snapshot: Optional[List[str]] = None,
    triggering_investigation_id: Optional[str] = None,
) -> int:
    """Append-only. NEVER call an UPDATE against this table from
    anywhere else -- every Steward re-evaluation of a candidate gets
    its own new row here, so the full confidence trajectory over time
    (the doc's section 8 example: 41% -> 49% -> 56% -> 44% -> 61%) is
    reconstructable, not just the current value."""
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        now = _now_iso()
        with conn:
            cursor = conn.execute(
                """
                INSERT INTO confidence_history
                    (candidate_id, recorded_at, band, numeric_confidence,
                     reasoning_snapshot_json, triggering_investigation_id)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                (
                    candidate_id, now, band, numeric_confidence,
                    json.dumps(reasoning_snapshot) if reasoning_snapshot is not None else None,
                    triggering_investigation_id,
                ),
            )
            return cursor.lastrowid
    finally:
        conn.close()


def get_confidence_history(db_root: str, candidate_id: str) -> List[Dict[str, Any]]:
    """Returns every confidence_history row for a candidate, oldest
    first -- the raw material for a future confidence-evolution chart."""
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        rows = conn.execute(
            "SELECT * FROM confidence_history WHERE candidate_id = ? ORDER BY id ASC",
            (candidate_id,),
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


# =========================== TIMELINE EVENT ===========================

def log_timeline_event(
    db_root: str,
    grand_project_id: str,
    event_type: str,
    related_entity_type: Optional[str] = None,
    related_entity_id: Optional[str] = None,
    description: str = "",
) -> int:
    """Append-only, exactly like confidence_history. Every other
    function in this module that changes something meaningful already
    calls this itself -- callers outside this module should still feel
    free to log additional events (e.g. field-verification updates)
    directly through this function."""
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        now = _now_iso()
        with conn:
            cursor = conn.execute(
                """
                INSERT INTO timeline_event
                    (grand_project_id, occurred_at, event_type,
                     related_entity_type, related_entity_id, description)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                (grand_project_id, now, event_type, related_entity_type,
                 related_entity_id, description),
            )
            return cursor.lastrowid
    finally:
        conn.close()


def get_timeline(db_root: str, grand_project_id: str) -> List[Dict[str, Any]]:
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        rows = conn.execute(
            "SELECT * FROM timeline_event WHERE grand_project_id = ? ORDER BY id ASC",
            (grand_project_id,),
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


# =========================== EVIDENCE GRAPH (READ-ONLY, PHASE 2 preview) ===========================

def get_candidate_evidence(db_root: str, candidate_id: str) -> List[Dict[str, Any]]:
    """Returns every evidence_link row for one candidate -- the raw
    material Phase 2's Evidence Graph traversal will build on. Included
    here (rather than deferred entirely to Phase 2) because it's a
    trivial read against Phase 0's own schema and is useful for
    debugging/verifying Phase 0 itself before Phase 2 exists."""
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        rows = conn.execute(
            "SELECT * FROM evidence_link WHERE candidate_id = ? ORDER BY id ASC",
            (candidate_id,),
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def get_grand_project(db_root: str, grand_project_id: str) -> Optional[Dict[str, Any]]:
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        row = conn.execute(
            "SELECT * FROM grand_project WHERE id = ?", (grand_project_id,)
        ).fetchone()
        return dict(row) if row is not None else None
    finally:
        conn.close()


def list_candidates_for_project(db_root: str, grand_project_id: str) -> List[Dict[str, Any]]:
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        rows = conn.execute(
            "SELECT * FROM candidate WHERE grand_project_id = ? ORDER BY created_at ASC",
            (grand_project_id,),
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


# =========================== INVESTIGATION (READ, ADDED 2026-09-16, Phase 2) ===========================

def list_investigations_for_project(db_root: str, grand_project_id: str) -> List[Dict[str, Any]]:
    """Returns every investigation row for a project, oldest first.
    ADDED for Phase 2 (Confidence History + Evidence Graph +
    Hypothesis objects UI): create_investigation()/complete_investigation()
    have existed since Phase 0, but nothing ever read them back as a
    list -- a genuine gap discovered while scoping Phase 2's
    "Investigations" flat list, not something worked around. Mirrors
    list_candidates_for_project()'s own pattern exactly."""
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        rows = conn.execute(
            "SELECT * FROM investigation WHERE grand_project_id = ? ORDER BY created_at ASC",
            (grand_project_id,),
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


# =========================== HISTORICAL FINDING (ADDED 2026-09-16, Phase 2.5 Item 3) ===========================

def create_historical_finding(
    db_root: str,
    grand_project_id: str,
    source_type: str,
    item_detail: Dict[str, Any],
    retrieved_at: str,
    title: Optional[str] = None,
    url: Optional[str] = None,
    hypothesis_id: Optional[str] = None,
) -> str:
    """Records ONE real historical-research item (a Wikipedia/
    Wikisource/Internet Archive hit) that backed at least one geographic
    suggestion. `item_detail` is stored as-is as JSON, in full -- the
    SAME real item dict historical_source_mobile_combined.py's own
    fetch_combined_historical_evidence() already produced for this item,
    reused rather than reshaped, matching add_evidence_link()'s own
    `detail` convention above. `title`/`url` are ALSO pulled out into
    their own columns purely so callers can query/display without
    parsing item_detail_json every time -- item_detail remains the
    single source of truth for anything not covered by a dedicated
    column (e.g. `snippet` vs `description`, which differ by source
    module and are therefore not each given their own column here).

    See this module's docstring and the historical_finding/
    geographic_suggestion schema comment for why this is a NEW table
    rather than an evidence_link row: this fires BEFORE any DEM
    candidate exists, often before any investigation has run at all.

    `retrieved_at` is the caller-supplied retrieval_date string from the
    real fetch_combined_historical_evidence() result (NOT independently
    regenerated here) -- this preserves the actual moment the research
    was fetched, not the (possibly much later, if a caller batches
    persistence) moment it was written to the database; created_at below
    is separately generated for exactly that "when was this DB row
    written" distinction."""
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        finding_id = _new_id()
        now = _now_iso()
        with conn:
            conn.execute(
                """
                INSERT INTO historical_finding
                    (id, grand_project_id, hypothesis_id, source_type, title,
                     url, item_detail_json, retrieved_at, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    finding_id, grand_project_id, hypothesis_id, source_type,
                    title, url, json.dumps(item_detail), retrieved_at, now,
                ),
            )
        log_timeline_event(
            db_root, grand_project_id, "HISTORICAL_FINDING_RECORDED",
            related_entity_type="historical_finding", related_entity_id=finding_id,
            description=f"Historical finding recorded from {source_type}: {title or '(untitled)'}",
        )
        return finding_id
    finally:
        conn.close()


def get_historical_findings_for_project(db_root: str, grand_project_id: str) -> List[Dict[str, Any]]:
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        rows = conn.execute(
            "SELECT * FROM historical_finding WHERE grand_project_id = ? ORDER BY created_at ASC",
            (grand_project_id,),
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


# =========================== GEOGRAPHIC SUGGESTION (ADDED 2026-09-16, Phase 2.5 Item 3) ===========================

def add_geographic_suggestion(
    db_root: str,
    grand_project_id: str,
    kind: str,
    hypothesis_id: Optional[str] = None,
    historical_finding_id: Optional[str] = None,
    place_name: Optional[str] = None,
    resolved_name: Optional[str] = None,
    lat: Optional[float] = None,
    lon: Optional[float] = None,
    bounding_box: Optional[Dict[str, float]] = None,
    radius_value: Optional[float] = None,
    radius_unit: Optional[str] = None,
    radius_raw_text: Optional[str] = None,
    has_proximity_keyword: Optional[bool] = None,
    context: Optional[str] = None,
) -> str:
    """Records ONE suggestion produced by
    historical_claim_extraction_mobile.suggest_probable_areas(). NEVER a
    committed search area -- `status` defaults to 'PENDING_REVIEW' and
    this project's own design (user's mockup panel: "Research Hypothesis
    -- Not a Claim") requires a human to review/promote/reject every row
    here before it feeds any real AOI/tiling step. No rows are ever
    silently filtered out before being written -- see this project's
    2026-09-16 decision to persist every suggestion the extractor
    produces, including ungrounded/noisy ones, rather than pre-filtering
    for relevance (deferred to Phase 5, once real outcome data exists to
    validate a filtering rule against).

    `kind` MUST be one of 'PAIRED_SUGGESTION' / 'DISTANCE_ONLY' /
    'UNGROUNDED_PLACE' (not DB-enforced, matching this project's existing
    convention of leaving free-text columns unconstrained for forward
    compatibility -- see add_evidence_link()'s own `relation` note).
    The three kinds genuinely carry different real fields, matching
    exactly what suggest_probable_areas() itself returns for each list
    (NOT padded with fabricated values for fields a given kind never
    has):
      - PAIRED_SUGGESTION: place_name/resolved_name/lat/lon/bounding_box
        (from the real Nominatim anchor) + radius_value/unit/raw_text +
        context + historical_finding_id. has_proximity_keyword is
        correctly NULL here -- suggest_probable_areas() strips that
        field out of the "radius" sub-dict for suggested_areas entries,
        it is only ever present on distance_only_mentions.
      - DISTANCE_ONLY: radius_value/unit/raw_text + has_proximity_keyword
        + context. No place_name/lat/lon/bounding_box/historical_finding_id
        -- distance_only_mentions carries no source_item at all in the
        real suggest_probable_areas() output, so there is nothing to
        link to a historical_finding row.
      - UNGROUNDED_PLACE: place_name only (the bare candidate string).
        No radius/context/historical_finding_id -- ungrounded_place_
        candidates is a flat list of strings in the real output, with no
        other fields attached to lose.

    `bounding_box`, if given, is stored as JSON -- the SAME real
    bounding_box dict geocode_place_name() already returns
    (min_lat/max_lat/min_lon/max_lon), reused rather than reshaped."""
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        suggestion_id = _new_id()
        now = _now_iso()
        with conn:
            conn.execute(
                """
                INSERT INTO geographic_suggestion
                    (id, grand_project_id, hypothesis_id, historical_finding_id,
                     kind, place_name, resolved_name, lat, lon,
                     bounding_box_json, radius_value, radius_unit,
                     radius_raw_text, has_proximity_keyword, context,
                     status, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'PENDING_REVIEW', ?)
                """,
                (
                    suggestion_id, grand_project_id, hypothesis_id, historical_finding_id,
                    kind, place_name, resolved_name, lat, lon,
                    json.dumps(bounding_box) if bounding_box is not None else None,
                    radius_value, radius_unit, radius_raw_text,
                    (None if has_proximity_keyword is None else int(bool(has_proximity_keyword))),
                    context, now,
                ),
            )
        log_timeline_event(
            db_root, grand_project_id, "GEOGRAPHIC_SUGGESTION_RECORDED",
            related_entity_type="geographic_suggestion", related_entity_id=suggestion_id,
            description=f"Geographic suggestion recorded ({kind}): {place_name or '(no place name)'}",
        )
        return suggestion_id
    finally:
        conn.close()


def update_geographic_suggestion_status(
    db_root: str, grand_project_id: str, suggestion_id: str, new_status: str
) -> None:
    """Changes ONLY the status column (e.g. a human reviewer setting it
    to 'ACCEPTED'/'REJECTED') -- the row itself is never deleted, same
    "dead ends are retained evidence" rule as
    update_candidate_status() above."""
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        with conn:
            conn.execute(
                "UPDATE geographic_suggestion SET status = ? WHERE id = ?",
                (new_status, suggestion_id),
            )
        log_timeline_event(
            db_root, grand_project_id, "GEOGRAPHIC_SUGGESTION_STATUS_CHANGED",
            related_entity_type="geographic_suggestion", related_entity_id=suggestion_id,
            description=f"Geographic suggestion status changed to {new_status}.",
        )
    finally:
        conn.close()


def get_geographic_suggestions_for_project(db_root: str, grand_project_id: str) -> List[Dict[str, Any]]:
    conn = get_connection(db_root)
    try:
        initialize_schema(conn)
        rows = conn.execute(
            "SELECT * FROM geographic_suggestion WHERE grand_project_id = ? ORDER BY created_at ASC",
            (grand_project_id,),
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()